<a href="https://colab.research.google.com/github/kokikudo/submit_an_assignment/blob/master/Week2%E6%8E%88%E6%A5%AD%E5%89%8D%E8%AA%B2%E9%A1%8C3_%E8%A1%8C%E5%88%97%E7%A9%8D%E3%81%AE%E3%82%B9%E3%82%AF%E3%83%A9%E3%83%83%E3%83%81.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1.テキストの目的
* Numpyに慣れる
* 行列演算に慣れる

## 2.　やること
以下の行列積を手計算で行い、スクラッチ実装することで理解を深める。

$$
A = 
  \left[\begin{array}{c}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
            7 & 8 & -9 \\
  \end{array}\right], \quad
B = 
  \left[\begin{array}{c}
            0 & 2 & 1 \\
            0 & 2 & -8 \\
            2 & 9 & -1 \\
  \end{array}\right] \quad
$$

In [22]:
import numpy as np
a_ndarray = np.array([
                      [-1, 2, 3],
                      [4, -5, 6],
                      [7, 8, -9],
                      ])
b_ndarray = np.array([
                      [0, 2, 1],
                      [0, 2, -8],
                      [2, 9, -1],
                      ])

___
### 問題1　行列積を手計算する

Aの0行の要素とBの0列の要素をそれぞれ掛け算し、その総和が新たな配列の要素となる。

$$
A = 
  \left[\begin{array}{c}
            a_1 & a_2 & a_3 \\
            a_4 & a_5 & a_6 \\
            a_7 & a_8 & a_9 \\
  \end{array}\right], \quad
B = 
  \left[\begin{array}{c}
            b_1 & b_2 & b_3 \\
            b_4 & b_5 & b_6 \\
            b_7 & b_8 & b_9 \\
  \end{array}\right] \quad
$$

だとすると、行列Aと行列Bの行列積ABは、、、

$$
AB = 
  \left[\begin{array}{c}
            a_1b_1+a_2b_4+a_3b_7 & a_1b_2+a_2b_5+a_3b_8 & a_1b_3+a_2b_6+a_3b_9 \\
            a_4b_1+a_5b_4+a_6b_7 & a_4b_2+a_5b_5+a_6b_8 & a_4b_3+a_5b_6+a_6b_9 \\
            a_7b_1+a_8b_4+a_9b_7 & a_7b_2+a_8b_5+a_9b_8 & a_7b_3+a_8b_6+a_9b_9 \\
  \end{array}\right] \quad
$$

よって、
$$
AB = 
  \left[\begin{array}{c}
            (-1*0)+(2*0)+(3*2) & (-1*2)+(2*2)+(3*9) & (-1*1)+(2*-8)+(3*-1) \\
            (4*0)+(-5*0)+(6*2) & (4*2)+(-5*2)+(6*9) & (4*1)+(-5*-8)+(6*-1) \\
            (7*0)+(8*0)+(-9*2) & (7*2)+(8*2)+(-9*9) & (7*1)+(8*-8)+(-9*-1) \\
  \end{array}\right] \quad
AB = 
  \left[\begin{array}{c}
            6 & 29 & -20 \\
            12 & 52 & 38 \\
            -18 & -51 & -48 \\
  \end{array}\right] \quad
$$


___
### 問題2　Numpyの関数を使って計算
Numpyを使って計算する方法は3種類ある。それぞれ試してみる。

In [23]:
# np.matmul()
matmul_A_B = np.matmul(a_ndarray, b_ndarray)
matmul_A_B

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [24]:
# @
at_sign_A_B = a_ndarray @ b_ndarray
at_sign_A_B


array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [25]:
# np.dot()
dot_A_B = np.dot(a_ndarray, b_ndarray)
dot_A_B

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## 3.行列積のスクラッチ実装
問題2で使った関数（と演算子）を使わずに手計算で行った計算過程をNumpyによるスクラッチ実装で再現してみる。

___
### 問題3　ある要素の計算を実装
行列Aの0行と行列Bの0列の計算は、以下の式で表せる。
$$
\sum_{k=0}^{2}a_0,_k b_k,_0 \quad
$$


In [60]:
rowA0_columnB0 = np.sum([a_ndarray[0][k] * b_ndarray[k][0] for k in range(a_ndarray.shape[0])])
rowA0_columnB0

6

___
### 問題4　関数の作成
行列Aと行列Bを引数として、行列積を返す関数を作る。
$$
c_i,_j = \sum_{k=0}^{2}a_i,_k b_k,_j \quad
$$

In [45]:
def matrix_ab(a, b):
    # 計算後のshapeの配列（要素が全て0）を先に作成
    # 例）(2, 3)と（3, 4）の積の場合は(2, 4)
    c = np.zeros((a.shape[0], b.shape[1]), dtype=a.dtype)

    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                # c[i, j]の要素0にa[i, k] * b[k, j]を加算
                c[i, j] += a[i, k] * b[k, j]
    return c

print('AとBの行列積C=\n', matrix_ab(a_ndarray, b_ndarray))

AとBの行列積C=
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


##4.行列積が定義されない組み合わせの行列
以下の行列の積を考える。
$$
D = 
  \left[\begin{array}{c}
            -1 & 2 & 3 \\
            4 & -5 & 6 \\
  \end{array}\right], \quad
E = 
  \left[\begin{array}{c}
            -9 & 8 & 7 \\
            6 & -5 & 4 \\
  \end{array}\right] \quad
$$

In [46]:
d_ndarray = np.array([
                      [-1, 2, 3],
                      [4, -5, 6],
                      ])
e_ndarray = np.array([
                      [-9, 8, 7],
                      [6, -5, 4],
                      ])

___
### 問題5　計算が定義されてない入力を判定する
Dの列数とEの行数が違うため行列積の計算ができない。<br>
問題4で作った関数に通すとエラーになる。<br>
エラーを回避するため、第一引数の行列の列数と第二引数の行列の行数が一致しているかの確認処理を追加する。

In [52]:
def matrix_ab(a, b):
    if a.shape[1] != b.shape[0]:
        return '第一引数の行列の列数と第二引数の行列の行数が一致していないため計算できません。'

    c = np.zeros((a.shape[0], b.shape[1]), dtype=a.dtype)
    for i in range(a.shape[0]):
        for j in range(b.shape[1]):
            for k in range(a.shape[1]):
                c[i, j] += a[i, k] * b[k, j]
    return c

print(matrix_ab(d_ndarray, e_ndarray))

第一引数の行列の列数と第二引数の行列の行数が一致していないため計算できません。


___
### 問題6　転置
転置して計算してみる。

In [58]:
# np.transpose()
trans_e_ndarray = np.transpose(e_ndarray)
print('D=\n', d_ndarray)
print('転置済E=\n', trans_e_ndarray)
print('Dと転置Eの行列積=\n', matrix_ab(d_ndarray, trans_e_ndarray))

D=
 [[-1  2  3]
 [ 4 -5  6]]
転置済E=
 [[-9  6]
 [ 8 -5]
 [ 7  4]]
Dと転置Eの行列積=
 [[ 46  -4]
 [-34  73]]


In [59]:
# もっと簡単な　.T
print(matrix_ab(d_ndarray, e_ndarray.T))

[[ 46  -4]
 [-34  73]]


## 5.感想
スクラッチ実装が難しかった。単純な繰り返し処理の組み合わせなのに頭がパンクしそうになった。paizaのスキルチェックでもfor文が積み重なった実装が苦手なので、克服できるようにしたい。