<a href="https://colab.research.google.com/github/kokikudo/submit_an_assignment/blob/master/Week4_work3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


## **【問題1】これまで利用してきたクラスの列挙**
クラスを使う際はインスタンス化を行うことと、クラスの命名法がわかりました。この情報を元に、これまでの課題で利用してきたコードの中でどのようなクラスがあったかを答えてください。


Pandas、matplotlib、scikit-learnからそれぞれ1つ以上見つけてください。

In [ ]:
# Pandasのクラスを一部出力
import pandas as pd
import inspect

classes = list(map(lambda x:x[0], inspect.getmembers(pd, inspect.isclass)))
classes[:5]

['BooleanDtype',
 'Categorical',
 'CategoricalDtype',
 'CategoricalIndex',
 'DataFrame']

In [ ]:
# matplotlib
import matplotlib
classes = list(map(lambda x:x[0], inspect.getmembers(matplotlib, inspect.isclass)))
classes[:5]

['ExecutableNotFoundError',
 'LooseVersion',
 'MatplotlibDeprecationWarning',
 'MutableMapping',
 'Parameter']

sklearnはdatasetsやmetrics、modelselection、linear_modelなどがあった。

**メソッド**

インスタンス化を行った後には、scaler.fit(X)のような メソッド の実行ができます。StandardScalerのfitメソッドは後でスケーリングに使われる平均と標準偏差を計算する機能があります。


**インスタンス変数（アトリビュート）**

fitメソッドにより平均と標準偏差が計算されましたが、見た目には変化があるわけではありません。しかし、scalerインスタンスの内部では計算結果が保存されています。こういったインスタンスの中で値を保存するものを インスタンス変数 や アトリビュート（属性） と呼びます。ここで平均がscaler.mean_、標準偏差の2乗した値である分散がscaler.var_に保存されています。


以下のようにprint文で出力させることができます。

In [ ]:
print("平均 : {}".format(scaler.mean_)) # 平均 : [4.86 3.31 1.45 0.22]
print("分散 : {}".format(scaler.var_)) # 分散 : [0.0764 0.0849 0.0105 0.0056]

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


## **【問題2】これまで利用してきたメソッドやインスタンス変数の列挙**
これまでの課題で利用してきたコードの中でどのようなメソッドやインスタンス変数があったかを答えてください。


最低でもそれぞれ5つ以上答えてください。

* メソッド
1. ndarray.sum()
2.pandas.DataFrame.groupby()
3.range()
4.zip()
5.matplotlib.pyplot.scatter


* インスタンス変数
1. ndarray.shape
2.pandas.DataFrame.columns
3.pandas.DataFrame.index
4.ndarray.dtype
5.ndarray.T


## **【問題3】標準化クラスをスクラッチで作成**
ポイント：雛形を元にして、標準化は何をしているのかを調査して、実装しましょう！
理解をより深めるため、StandardScalerをスクラッチで作成しましょう。scikit-learnは使わず、NumPyなどを活用して標準化の計算を記述します。具体的にはfitメソッドとtransformメソッドを作ります。

In [58]:
class ScratchStandardScaler():
    """
    標準化のためのクラス

    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = X.mean(axis=0)
        self.var_ = X.var(axis=0)
        
    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。

        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量

        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        #説明変数-その列の平均値 / 各列の標準偏差の平方根
        X_scaled = (X - self.mean_) / np.sqrt(self.var_)
        return X_scaled

In [59]:
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 :", scratch_scaler.mean_)
print("分散 :", scratch_scaler.var_)
X_std = scratch_scaler.transform(X)
print(X_std)

print('X_std mean: {:.1f}, std: {:.1f}'.format(X_std.mean(), X_std.var()))

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]
X_std mean: 0.0, std: 1.0


In [60]:
# 既存の標準化メソッドと出力の比較
scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


## **【問題4】 四則演算を行うクラスの作成**
上記ExampleClassは足し算のメソッドを持っていますが、これに引き算、掛け算、割り算のメソッドを加えてください。


コンストラクタに入力されたvalueが文字列や配列など数値以外だった場合にはエラーを出すようにしてください。


クラス名や説明文も適切に書き換えてください。

In [66]:
import warnings

In [95]:
class FourArithmeticOperations():
    """
    四則演算するクラス。
    引数を初期値に設定。
    計算後は更新されるので注意。
    例）　
    example = FourArithmeticOperations(5)
    example.add(3)
    ==> 8

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        try:
            value+1
            self.value = value
            print("初期値{}が設定されました".format(self.value))
        except TypeError:
            print('数値を渡してください！！')
    def add(self, value):
        """
        受け取った引数をself.valueに加える
        """
        try:
            value+1
            self.value += value
        except TypeError:
            print('数値を渡してください！！')
    def sub(self, value):
        """
        受け取った引数をself.valueに引き算する
        """
        try:
            value+1
            self.value -= value
        except TypeError:
            print('数値を渡してください！！')
    def mul(self, value):
        """
        受け取った引数をself.valueに掛け算する
        """
        try:
            value+1
            self.value *= value
        except TypeError:
            print('数値を渡してください！！')
    def div(self, value):
        """
        受け取った引数をself.valueに割り算する
        """
        try:
            value+1
            self.value /= value
        except TypeError:
            print('数値を渡してください！！')

example = FourArithmeticOperations(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.sub(4)
print("value : {}".format(example.value))
example.mul(2)
print("value : {}".format(example.value))
example.div(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8
value : 4
value : 8
value : 2.6666666666666665


In [96]:
# エラーメッセージの表示確認
example2 = FourArithmeticOperations("aaa")
example2 = FourArithmeticOperations(2)
example2.add('吉田')
example2.sub('岡本')
example2.mul('apple')
example2.div([1, 2, 3, 4])

数値を渡してください！！
初期値2が設定されました
数値を渡してください！！
数値を渡してください！！
数値を渡してください！！
数値を渡してください！！


## **感想**
progateでクラスの概念を少しだけ知っていたので、学習する上での抵抗感はなかった。が、課題に取り組んでる時やテキスト学習している時など、頭が一杯いっぱいの状態で自作するのは、現状はまだ難しいと感じた。